name = "RxEnvironments"
uuid = "5ea003d0-0c30-4e5c-84d5-cc22d8d83890"
authors = ["Wouter Nuijten"]
version = "0.2.10"

[deps]
Exceptions = "25a0344a-2aab-46d0-b534-6f1410d4c65f"
Rocket = "df971d30-c9d6-4b37-b8ff-e965b2cb3a40"

[weakdeps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
RxEnvironmentsPlottingExt = "GLMakie"

[compat]
Aqua = "0.8"
Coverage = "1.6"
DifferentialEquations = "~7.11"
Exceptions = "0.1"
GLMakie = "0.9"
ReTestItems = "1.20"
Rocket = "1"
Test = "<0.0.1, 1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Coverage", "ReTestItems", "Test"]
